### PR TITLE
Add php7-sqlite3 for rc4 

### PR DESCRIPTION
**Pull request by martadinata666**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-diskover/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
Addded dependencies for diskover rc4, as rc4 will store user & pass to sqlite db

## Benefits of this PR and context:
supporting rc4

### References
https://github.com/diskoverdata/diskover-community/blob/master/diskover-web/CHANGELOG.md

### CODE REVIEW

**Comment by serkef** [comment]
Can we get this merged? Current release v2.0-rc.4-ls49 is unusable without this change.
I just tested it and this changes solves the issue.

**Comment by TheSpad** [comment]
Please add a changelog note to the readme-vars and then I'm happy to merge this.

**Comment by martadinata666** [comment]
dd.mm.yy right?

**Comment by aptalca** [comment]
yup

**Comment by martadinata666** [comment]
thanks, anything still miss?

**Review by aptalca — APPROVED** [review]

**Comment by aptalca** [comment]
thanks for the PR, it should push a new image in about 15 minutes or so

**Pull request merged**
